Set Feature/post entity
kakao-tech-campus-2nd-step3/Team29_BE pull request #18
Opened 2024-09-20 12:33 UTC by Shsin9797

## 🔎 작업 내용

> Post 도메인의 테이블, 컬럼값 부분 구현했습니다. 

## 💬 리뷰 요구사항 (선택)

> post 랑 comment 를 동시에 작업하면서 번갈아서 push 했는데.. post 랑 comment 나눠서 올라가지않고 섞여서 올라간거같아요... 원래 이렇게 안하고 하나씩 작업해야하나요 ? 

## 📸 이미지 첨부 (선택)

## ➕ 이슈 링크

- [ Feature/post  #6] https://github.com/kakao-tech-campus-2nd-step3/Team29_BE/issues/6

2024-09-20 12:57 UTC, yunjunghun0116 approved these changes
고생하셨습니다 :)

2024-09-22 05:38 UTC, rladbrua0207 requested changes
고생하셨습니다!

수정 필요한부분 수정해주시면 Approve하겠습니다!

2024-09-22 05:38 UTC, rladbrua0207 commented on src/main/java/notai/comment/domain/Comment.java
필드명을 member_id라고 작성 안하셔도 Hibernate에서 알아서 memberId라고 했을경우 member_id로 알아서 매핑해주더라구요

저도 어떻게되는건지 궁금해서 찾아봤는데
https://docs.jboss.org/hibernate/orm/6.2/userguide/html_single/Hibernate_User_Guide.html#PhysicalNamingStrategy
여기에서 2.5. Naming strategies 부분 보시면 개발자가 작성한 엔티티 클래스 이름을 논리적 이름으로 결정하고 DB에 사용할때는 물리적 이름으로 변환하다고 하는 내용이 있는데
저희가 정한 이름 memberId를 인식하도록 논리적 이름으로 결정하고 이걸 DB에 저장할때 물리적이름으로 변환해서 member_id로 저장하는거 같더라구요 

private Long memberId 이런식으로 작성하시면 좋을 거 같습니다.

2024-09-22 05:38 UTC, rladbrua0207 commented on src/main/java/notai/comment/domain/Comment.java
column의 length를 기본적으로 지정해주는게 좋을 거 같아요 전에 멘토님께 피드백 받았던 내용인데 DB를 저희가 중간에 바꾸진 않겠지만 DB별로 default column length가 다르다보니 정해주는게 좋다고 하더라구요

2024-09-22 05:38 UTC, rladbrua0207 commented on src/main/java/notai/comment/domain/Comment.java
createdAt, updatedAt은 RootEntity에 구현돼있어서 따로 작성하지않으셔도 될 거 같아요

2024-09-22 05:38 UTC, rladbrua0207 commented on src/main/java/notai/comment/domain/Comment.java
@Auth는 생성자에서는 작성하지 않으셔도 되고 Controller에서 memberId가 필요할경우
<img width="590" alt="image" src="https://github.com/user-attachments/assets/3a277aa3-4b8a-475e-861b-9588770af9d7">
이렇게 사용하시면 될 거 같습니다!

2024-09-22 05:38 UTC, rladbrua0207 commented on src/main/java/notai/comment/domain/CommentRepository.java
자바에서는 Long으로 했을때 대부분? h2랑 mysql만 확인해봤는데 DB에는 bigint타입으로 저장되더라구요 Long으로 통일해주시면 좋을 거 같습니다!

2024-09-22 07:37 UTC, Shsin9797 commented on src/main/java/notai/comment/domain/Comment.java
자세한 설명 감사합니다 !! 

-- 참고 --
Hibernate의 명명 전략은 객체-관계 매핑(ORM)을 사용하는 개발자들에게 종종 혼란을 줄 수 있는 부분입니다.

논리적 이름과 물리적 이름, 무엇이 다른가요?
논리적 이름 (Logical Name):
개발자가 Java 클래스나 속성에 부여하는 이름입니다.
코드 가독성과 유지보수를 위해 의미 있는 이름을 사용합니다.
예: memberId, userAccount
물리적 이름 (Physical Name):
데이터베이스 테이블이나 컬럼에 실제로 사용되는 이름입니다.
데이터베이스 시스템의 제약이나 규칙에 맞춰야 합니다.
예: member_id, user_account
Hibernate의 명명 전략이 하는 일
Hibernate는 개발자가 정의한 논리적 이름을 데이터베이스에 맞는 물리적 이름으로 자동 변환해줍니다. 이 과정에서 다양한 명명 전략을 적용하여 개발자의 편의를 도모합니다.

예시:

개발자가 정의한 엔티티:
`
@Entity
public class Member {
    @Id
    private Long memberId;
    // ...
}
`
코드를 사용할 때는 [주의](https://github.com/faq#coding)가 필요합니다.

논리적 이름: memberId
물리적 이름: member_id (기본적인 언더스코어(_) 방식 변환)
왜 명명 전략이 필요한가요?
데이터베이스 시스템의 제약:
대소문자 구분, 특수 문자 사용 제한 등 데이터베이스마다 다른 규칙이 존재합니다.
코드와 데이터베이스의 일관성 유지:
개발자가 의도한 이름과 실제 데이터베이스에 저장된 이름이 다르면 혼란을 야기할 수 있습니다.
다양한 개발 스타일 지원:
개발자마다 선호하는 명명 규칙이 다르므로, Hibernate는 다양한 명명 전략을 제공하여 개발자의 선택지를 넓힙니다.
2.5. Naming strategies 부분의 의미
링크하신 Hibernate 문서의 2.5. Naming strategies 부분에서는 Hibernate가 제공하는 다양한 명명 전략에 대해 설명하고 있습니다. 즉, 개발자가 정의한 논리적 이름을 어떤 방식으로 물리적 이름으로 변환할지 설정할 수 있다는 것을 의미합니다.

추가 설명
ImplicitNamingStrategy: Hibernate가 기본적으로 제공하는 명명 전략으로, 대부분의 경우 자동으로 적절한 물리적 이름을 생성해줍니다.
PhysicalNamingStrategy: 개발자가 직접 구현하여 더욱 복잡한 명명 규칙을 적용할 수 있는 인터페이스입니다.
@Table, @Column 애노테이션: 개발자가 직접 물리적 이름을 지정할 수 있습니다.
결론
Hibernate의 명명 전략은 개발자가 객체 지향적인 방식으로 데이터베이스를 설계하고 관리할 수 있도록 도와줍니다. 논리적 이름과 물리적 이름의 개념을 이해하고, Hibernate가 제공하는 다양한 명명 전략을 적절히 활용하면 더욱 효율적인 개발이 가능합니다.

2024-09-22 07:53 UTC, Shsin9797 commented on src/main/java/notai/comment/domain/CommentRepository.java
넵 수정했습니다 !

2024-09-22 08:21 UTC, Shsin9797 commented on src/main/java/notai/comment/domain/Comment.java
궁금한사항 : length 지정시 , content 부분에 아래 방법을 사용하는건 어떻게 보시나요? 

* 긴 텍스트 저장: 게시글 본문, 댓글 등 긴 텍스트를 저장하는 경우라면 255자는 부족할 수 있습니다. 이 경우 TEXT 또는 CLOB 타입을 사용하는 것이 적절합니다.

게시글 본문: @Lob 애노테이션을 사용하여 CLOB 타입으로 설정하는 것이 좋습니다.

`
@Lob
private String contents; // 긴 텍스트 저장 시
`

2024-09-22 08:40 UTC, rladbrua0207 commented on src/main/java/notai/comment/domain/Comment.java
Post에서는 255자로 부족 할 수 있겠네요 Comment는 255를 넘을 거 같지는 않아서 유지하고 Post에서는 Lob쓰는거 좋아보입니다!

2024-09-22 08:52 UTC, Shsin9797 commented on src/main/java/notai/comment/domain/Comment.java
넵 수정했습니다!

2024-09-23 03:57 UTC, closed without merging